services:
  - type: web
    name: ncc-army-portal-api
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
